"""add_audio_metadata_to_meetings

Revision ID: ddd38f8a6fb0
Revises: 0540508442f9
Create Date: 2026-08-13 17:24:00.670222
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd38f8a6fb0'
down_revision = '0540508442f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('audio_file_path', sa.String(length=512), nullable=True))
    op.add_column('meetings', sa.Column('audio_filename', sa.String(length=255), nullable=True))
    op.add_column('meetings', sa.Column('audio_mime_type', sa.String(length=100), nullable=True))
    op.add_column('meetings', sa.Column('audio_size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('meetings', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'error_message')
    op.drop_column('meetings', 'audio_size_bytes')
    op.drop_column('meetings', 'audio_mime_type')
    op.drop_column('meetings', 'audio_filename')
    op.drop_column('meetings', 'audio_file_path')
    # ### end Alembic commands ###
